### ISSUE TITLE
open wav also if header not clean or edited by other app 

### ISSUE THREAD

**Issue by ohquait** [AlisterH/gwc#32]
just a idea and i knowing you have not all 24 hours of a day,
please check out the code of fre:ac, there are stable working code for use
such resampler and it can open wav mp3 ogg and so on to de-/re-encode to what you will have,
but first i should say **THANK YOU!** 
exactly this is was i missed many years in linux
i have packaed it and on the link bellow is a posting with screenshots about this
https://www.pclinuxos.com/forum/index.php/topic,159368.msg1375445.html#msg1375445

i hope this can help to integrate functions 
https://github.com/enzo1982/freac
this open wav also if header not clean or edited by other app 
of course i am not a coder, just a packager 
- hope the translator make it good enough -

**Comment by AlisterH** [comment]
I am not actively developing gwc and in the foreseeable future will not be looking at integrating anything else in it for converting/reencoding files.
FWIW I did think we might be able to resolve this by borrowing some code from mhwaveedit - since it is an audio editor and also uses sndfile, I hoped it might be fairly simple to replace some of our code with theirs.  Maybe it would be fairly simple for someone more competent, but IIRC I just found it too difficult to get my head around the relevant  code both in mhwaveedit and gwc.

**Comment by AlisterH** [comment]
BTW I see you said something about this formerly being called GWC.  It was called "Gnome Wave Cleaner" before I removed the old gnome dependencies, so that might be the name you should have been referring to.  Unless you just meant that there was a package named "gwc" in PCLinuxos.

**Comment by ohquait** [comment]
gwc was on older day's ~ 2010 on PCLinuxOS,
A you are right, the mhwaveedit is also builded with sndfile... cool....
what can i do to help ?
i have just one idea what i want have. and 10 thumbs all on left side ;)

**Comment by AlisterH** [comment]
Well, I'll certainly accept patches/pull requests.
But what is your idea?

**Comment by ohquait** [comment]
my idea, first i have to learn more about the app and testing with my older wavfiles,
then i will replying here....
in many cases the real problem sit in front of monitor ;)
